allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  esbuild: true
  inngest-cli: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - inngest-cli
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
