# https://taskfile.dev

version: '3'

silent: true

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all

  dev:
    desc: Runs mprocs
    deps:
      - install
    cmds:
      - task: db:generate
      - mprocs

  db:generate:
    desc: Generate prisma client
    deps:
      - install
    sources:
      - ./prisma/schema.prisma
    cmd: pnpm db:generate

  db:migrate:
    desc: Generate database migrations
    deps:
      - install
    sources:
      - ./prisma/schema.prisma
    cmd: pnpm db:migrate

  db:studio:
    desc: Runs prisma studio
    deps:
      - install
    cmd: pnpm db:studio

  format:
    desc: Runs prettier cli
    deps:
      - install
    cmd: pnpm format

  lint:
    desc: Runs 'next lint'
    deps:
      - install
    cmd: pnpm lint

  install:
    desc: Install depencencies
    status:
      - test -d node_modules # triggers if node_modules does not exists
    sources:
      - package.json
      - pnpm-lock.yaml
    cmds:
      - pnpm install

  reset:
    desc: Remove 'node_modules', '.next' and '.task' directories
    cmds:
      - rm -rf node_modules
      - rm -rf .next
      - rm -rf .task
